name: odlm_app
description: "객체 탐지를 통한 도서관 자리 관리 시스템"

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  flutterflow_ui: ^0.2.0+1
  styled_divider: 1.0.5
  auto_size_text: 3.0.0
  cached_network_image: 3.2.1
  collection: 1.18.0
  flutter_animate: 4.1.1+1
  flutter_cache_manager: 3.3.0
  font_awesome_flutter: 10.1.0
  from_css_color: 2.0.0
  go_router: 7.1.1
  google_fonts: 4.0.3
  intl: 0.18.1
  json_path: 0.6.2
  page_transition: 2.0.4
  path_provider: 2.0.14
  path_provider_android: 2.0.25
  path_provider_foundation: 2.2.2
  path_provider_platform_interface: 2.0.6
  provider: 6.0.4
  shared_preferences: 2.2.2
  shared_preferences_android: 2.2.1
  shared_preferences_foundation: 2.3.4
  shared_preferences_platform_interface: 2.3.1
  shared_preferences_web: 2.2.1
  sqflite: 2.2.6

  timeago: 3.2.2
  url_launcher: 6.2.5
  url_launcher_android: 6.3.0
  url_launcher_ios: 6.2.5
  url_launcher_platform_interface: 2.3.2


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6


dev_dependencies:
  flutter_lints: ^3.0.0
  lints: 3.0.0

  flutter_test:
    sdk: flutter



flutter:
  uses-material-design: true
  #  assets:
  #    - assets/images/
  #    - assets/videos/
  #    - assets/audios/
  #    - assets/lottie_animations/
  #    - assets/rive_animations/
  #    - assets/pdfs/

  assets:
    - assets/

